name: "Codecov"

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  schedule: 
    - cron: "34 12 * * 0"

jobs:
  upload:
    name: "Upload Code to Codecov"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Upload files (Codecov Action)
        uses: codecov/codecov-action@v3
        with:
          fail_ci_if_error: true
          verbose: true
