name: Prettier Check

on:
  push:
    branches: ["main"]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: ["main"]
  schedule:
    - cron: "40 15 * * 2"

jobs:
  prettier:
    name: Run prettier scanning
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup node and yarn
        uses: actions/setup-node@v2
        with:
          node-version: "18"
          cache: "yarn"

      - name: Install Prettier
        run: |
          yarn install

      - name: Run Prettier
        run: yarn prettier --check .
